"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CrossReference = void 0;
var typeorm_1 = require("typeorm");
var CrossReference = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('cross_references')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _sourceVerse_decorators;
    var _sourceVerse_initializers = [];
    var _sourceVerse_extraInitializers = [];
    var _targetVerse_decorators;
    var _targetVerse_initializers = [];
    var _targetVerse_extraInitializers = [];
    var _relationshipType_decorators;
    var _relationshipType_initializers = [];
    var _relationshipType_extraInitializers = [];
    var _strength_decorators;
    var _strength_initializers = [];
    var _strength_extraInitializers = [];
    var _isAutoGenerated_decorators;
    var _isAutoGenerated_initializers = [];
    var _isAutoGenerated_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var CrossReference = _classThis = /** @class */ (function () {
        function CrossReference_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.sourceVerse = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _sourceVerse_initializers, void 0));
            this.targetVerse = (__runInitializers(this, _sourceVerse_extraInitializers), __runInitializers(this, _targetVerse_initializers, void 0));
            this.relationshipType = (__runInitializers(this, _targetVerse_extraInitializers), __runInitializers(this, _relationshipType_initializers, void 0));
            this.strength = (__runInitializers(this, _relationshipType_extraInitializers), __runInitializers(this, _strength_initializers, void 0));
            this.isAutoGenerated = (__runInitializers(this, _strength_extraInitializers), __runInitializers(this, _isAutoGenerated_initializers, void 0));
            this.createdAt = (__runInitializers(this, _isAutoGenerated_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            __runInitializers(this, _createdAt_extraInitializers);
        }
        return CrossReference_1;
    }());
    __setFunctionName(_classThis, "CrossReference");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _sourceVerse_decorators = [(0, typeorm_1.Column)({ type: 'text' })];
        _targetVerse_decorators = [(0, typeorm_1.Column)({ type: 'text' })];
        _relationshipType_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _strength_decorators = [(0, typeorm_1.Column)({ type: 'integer', default: 5 })];
        _isAutoGenerated_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: true })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)({ type: 'timestamptz' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _sourceVerse_decorators, { kind: "field", name: "sourceVerse", static: false, private: false, access: { has: function (obj) { return "sourceVerse" in obj; }, get: function (obj) { return obj.sourceVerse; }, set: function (obj, value) { obj.sourceVerse = value; } }, metadata: _metadata }, _sourceVerse_initializers, _sourceVerse_extraInitializers);
        __esDecorate(null, null, _targetVerse_decorators, { kind: "field", name: "targetVerse", static: false, private: false, access: { has: function (obj) { return "targetVerse" in obj; }, get: function (obj) { return obj.targetVerse; }, set: function (obj, value) { obj.targetVerse = value; } }, metadata: _metadata }, _targetVerse_initializers, _targetVerse_extraInitializers);
        __esDecorate(null, null, _relationshipType_decorators, { kind: "field", name: "relationshipType", static: false, private: false, access: { has: function (obj) { return "relationshipType" in obj; }, get: function (obj) { return obj.relationshipType; }, set: function (obj, value) { obj.relationshipType = value; } }, metadata: _metadata }, _relationshipType_initializers, _relationshipType_extraInitializers);
        __esDecorate(null, null, _strength_decorators, { kind: "field", name: "strength", static: false, private: false, access: { has: function (obj) { return "strength" in obj; }, get: function (obj) { return obj.strength; }, set: function (obj, value) { obj.strength = value; } }, metadata: _metadata }, _strength_initializers, _strength_extraInitializers);
        __esDecorate(null, null, _isAutoGenerated_decorators, { kind: "field", name: "isAutoGenerated", static: false, private: false, access: { has: function (obj) { return "isAutoGenerated" in obj; }, get: function (obj) { return obj.isAutoGenerated; }, set: function (obj, value) { obj.isAutoGenerated = value; } }, metadata: _metadata }, _isAutoGenerated_initializers, _isAutoGenerated_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        CrossReference = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return CrossReference = _classThis;
}();
exports.CrossReference = CrossReference;
