import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn } from 'typeorm';

@Entity('cross_references')
export class CrossReference {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'text' })
  sourceVerse: string;

  @Column({ type: 'text' })
  targetVerse: string;

  @Column({ type: 'text', nullable: true })
  relationshipType: string;

  @Column({ type: 'integer', default: 5 })
  strength: number;

  @Column({ type: 'boolean', default: true })
  isAutoGenerated: boolean;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;
}
