"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SermonWorkspace = exports.WorkspaceStatus = exports.StoryArc = exports.SermonStyle = void 0;
var typeorm_1 = require("typeorm");
var user_entity_1 = require("./user.entity");
var sermon_outline_entity_1 = require("./sermon-outline.entity");
var sermon_manuscript_entity_1 = require("./sermon-manuscript.entity");
var sermon_application_entity_1 = require("./sermon-application.entity");
var sermon_illustration_entity_1 = require("./sermon-illustration.entity");
var discussion_question_entity_1 = require("./discussion-question.entity");
var sermon_citation_entity_1 = require("./sermon-citation.entity");
var note_entity_1 = require("./note.entity");
var ai_conversation_entity_1 = require("./ai-conversation.entity");
var sermon_dna_analysis_entity_1 = require("./sermon-dna-analysis.entity");
var sermon_study_report_entity_1 = require("./sermon-study-report.entity");
var theological_center_analysis_entity_1 = require("./theological-center-analysis.entity");
var tension_analysis_entity_1 = require("./tension-analysis.entity");
var doctrinal_precision_check_entity_1 = require("./doctrinal-precision-check.entity");
var blind_spot_analysis_entity_1 = require("./blind-spot-analysis.entity");
var preaching_strategy_entity_1 = require("./preaching-strategy.entity");
var historical_context_enhanced_entity_1 = require("./historical-context-enhanced.entity");
var SermonStyle;
(function (SermonStyle) {
    SermonStyle["EXPOSITORY"] = "expository";
    SermonStyle["TOPICAL"] = "topical";
    SermonStyle["NARRATIVE"] = "narrative";
    SermonStyle["APOLOGETIC"] = "apologetic";
    SermonStyle["DEVOTIONAL"] = "devotional";
})(SermonStyle || (exports.SermonStyle = SermonStyle = {}));
var StoryArc;
(function (StoryArc) {
    StoryArc["PROBLEM_TRUTH_RESPONSE"] = "problem_truth_response";
    StoryArc["TENSION_TURN_RESOLUTION"] = "tension_turn_resolution";
    StoryArc["QUESTION_DISCOVERY_ANSWER"] = "question_discovery_answer";
    StoryArc["CHALLENGE_JOURNEY_TRANSFORMATION"] = "challenge_journey_transformation";
})(StoryArc || (exports.StoryArc = StoryArc = {}));
var WorkspaceStatus;
(function (WorkspaceStatus) {
    WorkspaceStatus["DRAFT"] = "draft";
    WorkspaceStatus["IN_PROGRESS"] = "in_progress";
    WorkspaceStatus["COMPLETED"] = "completed";
    WorkspaceStatus["ARCHIVED"] = "archived";
})(WorkspaceStatus || (exports.WorkspaceStatus = WorkspaceStatus = {}));
var SermonWorkspace = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('sermon_workspaces')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _userId_decorators;
    var _userId_initializers = [];
    var _userId_extraInitializers = [];
    var _user_decorators;
    var _user_initializers = [];
    var _user_extraInitializers = [];
    var _title_decorators;
    var _title_initializers = [];
    var _title_extraInitializers = [];
    var _seriesTitle_decorators;
    var _seriesTitle_initializers = [];
    var _seriesTitle_extraInitializers = [];
    var _mainPassage_decorators;
    var _mainPassage_initializers = [];
    var _mainPassage_extraInitializers = [];
    var _additionalPassages_decorators;
    var _additionalPassages_initializers = [];
    var _additionalPassages_extraInitializers = [];
    var _theme_decorators;
    var _theme_initializers = [];
    var _theme_extraInitializers = [];
    var _audienceProfile_decorators;
    var _audienceProfile_initializers = [];
    var _audienceProfile_extraInitializers = [];
    var _sermonGoals_decorators;
    var _sermonGoals_initializers = [];
    var _sermonGoals_extraInitializers = [];
    var _theologicalLens_decorators;
    var _theologicalLens_initializers = [];
    var _theologicalLens_extraInitializers = [];
    var _style_decorators;
    var _style_initializers = [];
    var _style_extraInitializers = [];
    var _storyArc_decorators;
    var _storyArc_initializers = [];
    var _storyArc_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _language_decorators;
    var _language_initializers = [];
    var _language_extraInitializers = [];
    var _metadata_decorators;
    var _metadata_initializers = [];
    var _metadata_extraInitializers = [];
    var _scriptureCache_decorators;
    var _scriptureCache_initializers = [];
    var _scriptureCache_extraInitializers = [];
    var _references_decorators;
    var _references_initializers = [];
    var _references_extraInitializers = [];
    var _sermonCore_decorators;
    var _sermonCore_initializers = [];
    var _sermonCore_extraInitializers = [];
    var _egwEnabled_decorators;
    var _egwEnabled_initializers = [];
    var _egwEnabled_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _outlines_decorators;
    var _outlines_initializers = [];
    var _outlines_extraInitializers = [];
    var _manuscripts_decorators;
    var _manuscripts_initializers = [];
    var _manuscripts_extraInitializers = [];
    var _applications_decorators;
    var _applications_initializers = [];
    var _applications_extraInitializers = [];
    var _illustrations_decorators;
    var _illustrations_initializers = [];
    var _illustrations_extraInitializers = [];
    var _discussionQuestions_decorators;
    var _discussionQuestions_initializers = [];
    var _discussionQuestions_extraInitializers = [];
    var _citations_decorators;
    var _citations_initializers = [];
    var _citations_extraInitializers = [];
    var _notes_decorators;
    var _notes_initializers = [];
    var _notes_extraInitializers = [];
    var _aiConversations_decorators;
    var _aiConversations_initializers = [];
    var _aiConversations_extraInitializers = [];
    var _dnaAnalyses_decorators;
    var _dnaAnalyses_initializers = [];
    var _dnaAnalyses_extraInitializers = [];
    var _studyReports_decorators;
    var _studyReports_initializers = [];
    var _studyReports_extraInitializers = [];
    var _theologicalCenterAnalyses_decorators;
    var _theologicalCenterAnalyses_initializers = [];
    var _theologicalCenterAnalyses_extraInitializers = [];
    var _tensionAnalyses_decorators;
    var _tensionAnalyses_initializers = [];
    var _tensionAnalyses_extraInitializers = [];
    var _doctrinalChecks_decorators;
    var _doctrinalChecks_initializers = [];
    var _doctrinalChecks_extraInitializers = [];
    var _blindSpotAnalyses_decorators;
    var _blindSpotAnalyses_initializers = [];
    var _blindSpotAnalyses_extraInitializers = [];
    var _preachingStrategies_decorators;
    var _preachingStrategies_initializers = [];
    var _preachingStrategies_extraInitializers = [];
    var _historicalContexts_decorators;
    var _historicalContexts_initializers = [];
    var _historicalContexts_extraInitializers = [];
    var SermonWorkspace = _classThis = /** @class */ (function () {
        function SermonWorkspace_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.userId = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _userId_initializers, void 0));
            this.user = (__runInitializers(this, _userId_extraInitializers), __runInitializers(this, _user_initializers, void 0));
            this.title = (__runInitializers(this, _user_extraInitializers), __runInitializers(this, _title_initializers, void 0));
            this.seriesTitle = (__runInitializers(this, _title_extraInitializers), __runInitializers(this, _seriesTitle_initializers, void 0));
            this.mainPassage = (__runInitializers(this, _seriesTitle_extraInitializers), __runInitializers(this, _mainPassage_initializers, void 0));
            this.additionalPassages = (__runInitializers(this, _mainPassage_extraInitializers), __runInitializers(this, _additionalPassages_initializers, void 0));
            this.theme = (__runInitializers(this, _additionalPassages_extraInitializers), __runInitializers(this, _theme_initializers, void 0));
            this.audienceProfile = (__runInitializers(this, _theme_extraInitializers), __runInitializers(this, _audienceProfile_initializers, void 0));
            this.sermonGoals = (__runInitializers(this, _audienceProfile_extraInitializers), __runInitializers(this, _sermonGoals_initializers, void 0));
            this.theologicalLens = (__runInitializers(this, _sermonGoals_extraInitializers), __runInitializers(this, _theologicalLens_initializers, void 0));
            this.style = (__runInitializers(this, _theologicalLens_extraInitializers), __runInitializers(this, _style_initializers, void 0));
            this.storyArc = (__runInitializers(this, _style_extraInitializers), __runInitializers(this, _storyArc_initializers, void 0));
            this.status = (__runInitializers(this, _storyArc_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            this.language = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _language_initializers, void 0));
            this.metadata = (__runInitializers(this, _language_extraInitializers), __runInitializers(this, _metadata_initializers, void 0));
            this.scriptureCache = (__runInitializers(this, _metadata_extraInitializers), __runInitializers(this, _scriptureCache_initializers, void 0));
            this.references = (__runInitializers(this, _scriptureCache_extraInitializers), __runInitializers(this, _references_initializers, void 0));
            this.sermonCore = (__runInitializers(this, _references_extraInitializers), __runInitializers(this, _sermonCore_initializers, void 0));
            this.egwEnabled = (__runInitializers(this, _sermonCore_extraInitializers), __runInitializers(this, _egwEnabled_initializers, void 0));
            this.createdAt = (__runInitializers(this, _egwEnabled_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            this.outlines = (__runInitializers(this, _updatedAt_extraInitializers), __runInitializers(this, _outlines_initializers, void 0));
            this.manuscripts = (__runInitializers(this, _outlines_extraInitializers), __runInitializers(this, _manuscripts_initializers, void 0));
            this.applications = (__runInitializers(this, _manuscripts_extraInitializers), __runInitializers(this, _applications_initializers, void 0));
            this.illustrations = (__runInitializers(this, _applications_extraInitializers), __runInitializers(this, _illustrations_initializers, void 0));
            this.discussionQuestions = (__runInitializers(this, _illustrations_extraInitializers), __runInitializers(this, _discussionQuestions_initializers, void 0));
            this.citations = (__runInitializers(this, _discussionQuestions_extraInitializers), __runInitializers(this, _citations_initializers, void 0));
            this.notes = (__runInitializers(this, _citations_extraInitializers), __runInitializers(this, _notes_initializers, void 0));
            this.aiConversations = (__runInitializers(this, _notes_extraInitializers), __runInitializers(this, _aiConversations_initializers, void 0));
            this.dnaAnalyses = (__runInitializers(this, _aiConversations_extraInitializers), __runInitializers(this, _dnaAnalyses_initializers, void 0));
            this.studyReports = (__runInitializers(this, _dnaAnalyses_extraInitializers), __runInitializers(this, _studyReports_initializers, void 0));
            this.theologicalCenterAnalyses = (__runInitializers(this, _studyReports_extraInitializers), __runInitializers(this, _theologicalCenterAnalyses_initializers, void 0));
            this.tensionAnalyses = (__runInitializers(this, _theologicalCenterAnalyses_extraInitializers), __runInitializers(this, _tensionAnalyses_initializers, void 0));
            this.doctrinalChecks = (__runInitializers(this, _tensionAnalyses_extraInitializers), __runInitializers(this, _doctrinalChecks_initializers, void 0));
            this.blindSpotAnalyses = (__runInitializers(this, _doctrinalChecks_extraInitializers), __runInitializers(this, _blindSpotAnalyses_initializers, void 0));
            this.preachingStrategies = (__runInitializers(this, _blindSpotAnalyses_extraInitializers), __runInitializers(this, _preachingStrategies_initializers, void 0));
            this.historicalContexts = (__runInitializers(this, _preachingStrategies_extraInitializers), __runInitializers(this, _historicalContexts_initializers, void 0));
            __runInitializers(this, _historicalContexts_extraInitializers);
        }
        return SermonWorkspace_1;
    }());
    __setFunctionName(_classThis, "SermonWorkspace");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _userId_decorators = [(0, typeorm_1.Column)({ type: 'uuid' })];
        _user_decorators = [(0, typeorm_1.ManyToOne)(function () { return user_entity_1.User; }, function (user) { return user.workspaces; }, { onDelete: 'CASCADE' }), (0, typeorm_1.JoinColumn)({ name: 'userId' })];
        _title_decorators = [(0, typeorm_1.Column)({ type: 'text' })];
        _seriesTitle_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _mainPassage_decorators = [(0, typeorm_1.Column)({ type: 'text' })];
        _additionalPassages_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _theme_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _audienceProfile_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _sermonGoals_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _theologicalLens_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _style_decorators = [(0, typeorm_1.Column)({ type: 'enum', enum: SermonStyle, nullable: true })];
        _storyArc_decorators = [(0, typeorm_1.Column)({ type: 'enum', enum: StoryArc, nullable: true })];
        _status_decorators = [(0, typeorm_1.Column)({ type: 'enum', enum: WorkspaceStatus, default: WorkspaceStatus.DRAFT })];
        _language_decorators = [(0, typeorm_1.Column)({ type: 'text', default: 'en' })];
        _metadata_decorators = [(0, typeorm_1.Column)({ type: 'jsonb', default: {} })];
        _scriptureCache_decorators = [(0, typeorm_1.Column)({ type: 'jsonb', nullable: true })];
        _references_decorators = [(0, typeorm_1.Column)({ type: 'jsonb', nullable: true, default: [] })];
        _sermonCore_decorators = [(0, typeorm_1.Column)({ type: 'jsonb', nullable: true })];
        _egwEnabled_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: false })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)({ type: 'timestamptz' })];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)({ type: 'timestamptz' })];
        _outlines_decorators = [(0, typeorm_1.OneToMany)(function () { return sermon_outline_entity_1.SermonOutline; }, function (outline) { return outline.workspace; })];
        _manuscripts_decorators = [(0, typeorm_1.OneToMany)(function () { return sermon_manuscript_entity_1.SermonManuscript; }, function (manuscript) { return manuscript.workspace; })];
        _applications_decorators = [(0, typeorm_1.OneToMany)(function () { return sermon_application_entity_1.SermonApplication; }, function (application) { return application.workspace; })];
        _illustrations_decorators = [(0, typeorm_1.OneToMany)(function () { return sermon_illustration_entity_1.SermonIllustration; }, function (illustration) { return illustration.workspace; })];
        _discussionQuestions_decorators = [(0, typeorm_1.OneToMany)(function () { return discussion_question_entity_1.DiscussionQuestion; }, function (question) { return question.workspace; })];
        _citations_decorators = [(0, typeorm_1.OneToMany)(function () { return sermon_citation_entity_1.SermonCitation; }, function (citation) { return citation.workspace; })];
        _notes_decorators = [(0, typeorm_1.OneToMany)(function () { return note_entity_1.Note; }, function (note) { return note.workspace; })];
        _aiConversations_decorators = [(0, typeorm_1.OneToMany)(function () { return ai_conversation_entity_1.AiConversation; }, function (conversation) { return conversation.workspace; })];
        _dnaAnalyses_decorators = [(0, typeorm_1.OneToMany)(function () { return sermon_dna_analysis_entity_1.SermonDnaAnalysis; }, function (analysis) { return analysis.workspace; })];
        _studyReports_decorators = [(0, typeorm_1.OneToMany)(function () { return sermon_study_report_entity_1.SermonStudyReport; }, function (report) { return report.workspace; })];
        _theologicalCenterAnalyses_decorators = [(0, typeorm_1.OneToMany)(function () { return theological_center_analysis_entity_1.TheologicalCenterAnalysis; }, function (analysis) { return analysis.workspace; })];
        _tensionAnalyses_decorators = [(0, typeorm_1.OneToMany)(function () { return tension_analysis_entity_1.TensionAnalysis; }, function (analysis) { return analysis.workspace; })];
        _doctrinalChecks_decorators = [(0, typeorm_1.OneToMany)(function () { return doctrinal_precision_check_entity_1.DoctrinalPrecisionCheck; }, function (check) { return check.workspace; })];
        _blindSpotAnalyses_decorators = [(0, typeorm_1.OneToMany)(function () { return blind_spot_analysis_entity_1.BlindSpotAnalysis; }, function (analysis) { return analysis.workspace; })];
        _preachingStrategies_decorators = [(0, typeorm_1.OneToMany)(function () { return preaching_strategy_entity_1.PreachingStrategy; }, function (strategy) { return strategy.workspace; })];
        _historicalContexts_decorators = [(0, typeorm_1.OneToMany)(function () { return historical_context_enhanced_entity_1.HistoricalContextEnhanced; }, function (context) { return context.workspace; })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _userId_decorators, { kind: "field", name: "userId", static: false, private: false, access: { has: function (obj) { return "userId" in obj; }, get: function (obj) { return obj.userId; }, set: function (obj, value) { obj.userId = value; } }, metadata: _metadata }, _userId_initializers, _userId_extraInitializers);
        __esDecorate(null, null, _user_decorators, { kind: "field", name: "user", static: false, private: false, access: { has: function (obj) { return "user" in obj; }, get: function (obj) { return obj.user; }, set: function (obj, value) { obj.user = value; } }, metadata: _metadata }, _user_initializers, _user_extraInitializers);
        __esDecorate(null, null, _title_decorators, { kind: "field", name: "title", static: false, private: false, access: { has: function (obj) { return "title" in obj; }, get: function (obj) { return obj.title; }, set: function (obj, value) { obj.title = value; } }, metadata: _metadata }, _title_initializers, _title_extraInitializers);
        __esDecorate(null, null, _seriesTitle_decorators, { kind: "field", name: "seriesTitle", static: false, private: false, access: { has: function (obj) { return "seriesTitle" in obj; }, get: function (obj) { return obj.seriesTitle; }, set: function (obj, value) { obj.seriesTitle = value; } }, metadata: _metadata }, _seriesTitle_initializers, _seriesTitle_extraInitializers);
        __esDecorate(null, null, _mainPassage_decorators, { kind: "field", name: "mainPassage", static: false, private: false, access: { has: function (obj) { return "mainPassage" in obj; }, get: function (obj) { return obj.mainPassage; }, set: function (obj, value) { obj.mainPassage = value; } }, metadata: _metadata }, _mainPassage_initializers, _mainPassage_extraInitializers);
        __esDecorate(null, null, _additionalPassages_decorators, { kind: "field", name: "additionalPassages", static: false, private: false, access: { has: function (obj) { return "additionalPassages" in obj; }, get: function (obj) { return obj.additionalPassages; }, set: function (obj, value) { obj.additionalPassages = value; } }, metadata: _metadata }, _additionalPassages_initializers, _additionalPassages_extraInitializers);
        __esDecorate(null, null, _theme_decorators, { kind: "field", name: "theme", static: false, private: false, access: { has: function (obj) { return "theme" in obj; }, get: function (obj) { return obj.theme; }, set: function (obj, value) { obj.theme = value; } }, metadata: _metadata }, _theme_initializers, _theme_extraInitializers);
        __esDecorate(null, null, _audienceProfile_decorators, { kind: "field", name: "audienceProfile", static: false, private: false, access: { has: function (obj) { return "audienceProfile" in obj; }, get: function (obj) { return obj.audienceProfile; }, set: function (obj, value) { obj.audienceProfile = value; } }, metadata: _metadata }, _audienceProfile_initializers, _audienceProfile_extraInitializers);
        __esDecorate(null, null, _sermonGoals_decorators, { kind: "field", name: "sermonGoals", static: false, private: false, access: { has: function (obj) { return "sermonGoals" in obj; }, get: function (obj) { return obj.sermonGoals; }, set: function (obj, value) { obj.sermonGoals = value; } }, metadata: _metadata }, _sermonGoals_initializers, _sermonGoals_extraInitializers);
        __esDecorate(null, null, _theologicalLens_decorators, { kind: "field", name: "theologicalLens", static: false, private: false, access: { has: function (obj) { return "theologicalLens" in obj; }, get: function (obj) { return obj.theologicalLens; }, set: function (obj, value) { obj.theologicalLens = value; } }, metadata: _metadata }, _theologicalLens_initializers, _theologicalLens_extraInitializers);
        __esDecorate(null, null, _style_decorators, { kind: "field", name: "style", static: false, private: false, access: { has: function (obj) { return "style" in obj; }, get: function (obj) { return obj.style; }, set: function (obj, value) { obj.style = value; } }, metadata: _metadata }, _style_initializers, _style_extraInitializers);
        __esDecorate(null, null, _storyArc_decorators, { kind: "field", name: "storyArc", static: false, private: false, access: { has: function (obj) { return "storyArc" in obj; }, get: function (obj) { return obj.storyArc; }, set: function (obj, value) { obj.storyArc = value; } }, metadata: _metadata }, _storyArc_initializers, _storyArc_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _language_decorators, { kind: "field", name: "language", static: false, private: false, access: { has: function (obj) { return "language" in obj; }, get: function (obj) { return obj.language; }, set: function (obj, value) { obj.language = value; } }, metadata: _metadata }, _language_initializers, _language_extraInitializers);
        __esDecorate(null, null, _metadata_decorators, { kind: "field", name: "metadata", static: false, private: false, access: { has: function (obj) { return "metadata" in obj; }, get: function (obj) { return obj.metadata; }, set: function (obj, value) { obj.metadata = value; } }, metadata: _metadata }, _metadata_initializers, _metadata_extraInitializers);
        __esDecorate(null, null, _scriptureCache_decorators, { kind: "field", name: "scriptureCache", static: false, private: false, access: { has: function (obj) { return "scriptureCache" in obj; }, get: function (obj) { return obj.scriptureCache; }, set: function (obj, value) { obj.scriptureCache = value; } }, metadata: _metadata }, _scriptureCache_initializers, _scriptureCache_extraInitializers);
        __esDecorate(null, null, _references_decorators, { kind: "field", name: "references", static: false, private: false, access: { has: function (obj) { return "references" in obj; }, get: function (obj) { return obj.references; }, set: function (obj, value) { obj.references = value; } }, metadata: _metadata }, _references_initializers, _references_extraInitializers);
        __esDecorate(null, null, _sermonCore_decorators, { kind: "field", name: "sermonCore", static: false, private: false, access: { has: function (obj) { return "sermonCore" in obj; }, get: function (obj) { return obj.sermonCore; }, set: function (obj, value) { obj.sermonCore = value; } }, metadata: _metadata }, _sermonCore_initializers, _sermonCore_extraInitializers);
        __esDecorate(null, null, _egwEnabled_decorators, { kind: "field", name: "egwEnabled", static: false, private: false, access: { has: function (obj) { return "egwEnabled" in obj; }, get: function (obj) { return obj.egwEnabled; }, set: function (obj, value) { obj.egwEnabled = value; } }, metadata: _metadata }, _egwEnabled_initializers, _egwEnabled_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, null, _outlines_decorators, { kind: "field", name: "outlines", static: false, private: false, access: { has: function (obj) { return "outlines" in obj; }, get: function (obj) { return obj.outlines; }, set: function (obj, value) { obj.outlines = value; } }, metadata: _metadata }, _outlines_initializers, _outlines_extraInitializers);
        __esDecorate(null, null, _manuscripts_decorators, { kind: "field", name: "manuscripts", static: false, private: false, access: { has: function (obj) { return "manuscripts" in obj; }, get: function (obj) { return obj.manuscripts; }, set: function (obj, value) { obj.manuscripts = value; } }, metadata: _metadata }, _manuscripts_initializers, _manuscripts_extraInitializers);
        __esDecorate(null, null, _applications_decorators, { kind: "field", name: "applications", static: false, private: false, access: { has: function (obj) { return "applications" in obj; }, get: function (obj) { return obj.applications; }, set: function (obj, value) { obj.applications = value; } }, metadata: _metadata }, _applications_initializers, _applications_extraInitializers);
        __esDecorate(null, null, _illustrations_decorators, { kind: "field", name: "illustrations", static: false, private: false, access: { has: function (obj) { return "illustrations" in obj; }, get: function (obj) { return obj.illustrations; }, set: function (obj, value) { obj.illustrations = value; } }, metadata: _metadata }, _illustrations_initializers, _illustrations_extraInitializers);
        __esDecorate(null, null, _discussionQuestions_decorators, { kind: "field", name: "discussionQuestions", static: false, private: false, access: { has: function (obj) { return "discussionQuestions" in obj; }, get: function (obj) { return obj.discussionQuestions; }, set: function (obj, value) { obj.discussionQuestions = value; } }, metadata: _metadata }, _discussionQuestions_initializers, _discussionQuestions_extraInitializers);
        __esDecorate(null, null, _citations_decorators, { kind: "field", name: "citations", static: false, private: false, access: { has: function (obj) { return "citations" in obj; }, get: function (obj) { return obj.citations; }, set: function (obj, value) { obj.citations = value; } }, metadata: _metadata }, _citations_initializers, _citations_extraInitializers);
        __esDecorate(null, null, _notes_decorators, { kind: "field", name: "notes", static: false, private: false, access: { has: function (obj) { return "notes" in obj; }, get: function (obj) { return obj.notes; }, set: function (obj, value) { obj.notes = value; } }, metadata: _metadata }, _notes_initializers, _notes_extraInitializers);
        __esDecorate(null, null, _aiConversations_decorators, { kind: "field", name: "aiConversations", static: false, private: false, access: { has: function (obj) { return "aiConversations" in obj; }, get: function (obj) { return obj.aiConversations; }, set: function (obj, value) { obj.aiConversations = value; } }, metadata: _metadata }, _aiConversations_initializers, _aiConversations_extraInitializers);
        __esDecorate(null, null, _dnaAnalyses_decorators, { kind: "field", name: "dnaAnalyses", static: false, private: false, access: { has: function (obj) { return "dnaAnalyses" in obj; }, get: function (obj) { return obj.dnaAnalyses; }, set: function (obj, value) { obj.dnaAnalyses = value; } }, metadata: _metadata }, _dnaAnalyses_initializers, _dnaAnalyses_extraInitializers);
        __esDecorate(null, null, _studyReports_decorators, { kind: "field", name: "studyReports", static: false, private: false, access: { has: function (obj) { return "studyReports" in obj; }, get: function (obj) { return obj.studyReports; }, set: function (obj, value) { obj.studyReports = value; } }, metadata: _metadata }, _studyReports_initializers, _studyReports_extraInitializers);
        __esDecorate(null, null, _theologicalCenterAnalyses_decorators, { kind: "field", name: "theologicalCenterAnalyses", static: false, private: false, access: { has: function (obj) { return "theologicalCenterAnalyses" in obj; }, get: function (obj) { return obj.theologicalCenterAnalyses; }, set: function (obj, value) { obj.theologicalCenterAnalyses = value; } }, metadata: _metadata }, _theologicalCenterAnalyses_initializers, _theologicalCenterAnalyses_extraInitializers);
        __esDecorate(null, null, _tensionAnalyses_decorators, { kind: "field", name: "tensionAnalyses", static: false, private: false, access: { has: function (obj) { return "tensionAnalyses" in obj; }, get: function (obj) { return obj.tensionAnalyses; }, set: function (obj, value) { obj.tensionAnalyses = value; } }, metadata: _metadata }, _tensionAnalyses_initializers, _tensionAnalyses_extraInitializers);
        __esDecorate(null, null, _doctrinalChecks_decorators, { kind: "field", name: "doctrinalChecks", static: false, private: false, access: { has: function (obj) { return "doctrinalChecks" in obj; }, get: function (obj) { return obj.doctrinalChecks; }, set: function (obj, value) { obj.doctrinalChecks = value; } }, metadata: _metadata }, _doctrinalChecks_initializers, _doctrinalChecks_extraInitializers);
        __esDecorate(null, null, _blindSpotAnalyses_decorators, { kind: "field", name: "blindSpotAnalyses", static: false, private: false, access: { has: function (obj) { return "blindSpotAnalyses" in obj; }, get: function (obj) { return obj.blindSpotAnalyses; }, set: function (obj, value) { obj.blindSpotAnalyses = value; } }, metadata: _metadata }, _blindSpotAnalyses_initializers, _blindSpotAnalyses_extraInitializers);
        __esDecorate(null, null, _preachingStrategies_decorators, { kind: "field", name: "preachingStrategies", static: false, private: false, access: { has: function (obj) { return "preachingStrategies" in obj; }, get: function (obj) { return obj.preachingStrategies; }, set: function (obj, value) { obj.preachingStrategies = value; } }, metadata: _metadata }, _preachingStrategies_initializers, _preachingStrategies_extraInitializers);
        __esDecorate(null, null, _historicalContexts_decorators, { kind: "field", name: "historicalContexts", static: false, private: false, access: { has: function (obj) { return "historicalContexts" in obj; }, get: function (obj) { return obj.historicalContexts; }, set: function (obj, value) { obj.historicalContexts = value; } }, metadata: _metadata }, _historicalContexts_initializers, _historicalContexts_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        SermonWorkspace = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return SermonWorkspace = _classThis;
}();
exports.SermonWorkspace = SermonWorkspace;
