"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnalysisPrompts = void 0;
exports.AnalysisPrompts = {
    tensionMapping: function (input) {
        return "You are a preaching mentor specializing in TENSION MAPPING. Preaching thrives on tension, not quick resolution.\n\nPASSAGE: ".concat(input.mainPassage, "\nTEXT: ").concat(input.passageText, "\n\nMANUSCRIPT EXCERPT: ").concat(input.manuscriptExcerpt, "\n\nTASK:\nIdentify TEXTUAL TENSIONS in the passage:\n1. PARADOXES - Apparent contradictions (\"dead yet alive\", \"saved by grace yet created for works\")\n2. UNRESOLVED PHRASES - Questions or statements left hanging\n3. THEOLOGICAL FRICTION - Concepts that create productive discomfort\n\nFor each tension:\n- Quote the exact text\n- Explain the tension\n- Suggest how to PRESERVE it before resolving\n- Check if the sermon resolves it too quickly\n\nAnalyze SERMON TENSION HANDLING:\n- Does the sermon preserve tension before resolving?\n- Does it resolve too quickly?\n- Rate timing: \"too_early\" / \"appropriate\" / \"unresolved\"\n\nGive TENSION PRESERVATION SCORE (0-100).\n\nReturn JSON:\n{\n  \"tensions\": [\n    {\n      \"type\": \"paradox\",\n      \"text\": \"Exact quote from passage\",\n      \"verseReference\": \"Verse ref\",\n      \"explanation\": \"What creates the tension\",\n      \"preservationStrategy\": \"How to hold this tension before resolving\"\n    }\n  ],\n  \"sermonTensionHandling\": [\n    {\n      \"tension\": \"The tension being addressed\",\n      \"isPreserved\": false,\n      \"resolutionTiming\": \"too_early\",\n      \"recommendation\": \"Specific advice\"\n    }\n  ],\n  \"tensionPreservationScore\": 65\n}\n\nRemember: Tension creates weight. Quick resolution creates shallowness.");
    },
    doctrinalPrecision: function (input) {
        return "You are a Seventh-day Adventist theological guard, ensuring doctrinal precision and consistency.\n\nPASSAGE: ".concat(input.mainPassage, "\nTEXT: ").concat(input.passageText, "\n\nSERMON THEME: ").concat(input.theme, "\nOUTLINE: ").concat(input.outline, "\nMANUSCRIPT EXCERPT: ").concat(input.manuscriptExcerpt, "\n\nTASK: Check doctrinal consistency in these categories:\n\n1. GRACE - Is it framed as forensic only, or does it include transformative power?\n2. SANCTIFICATION - Is it reduced to moral effort, or properly understood as Spirit-empowered growth?\n3. SABBATH - Is it framed as covenant sign or mere obligation?\n4. STATE OF THE DEAD - Is it consistent with soul sleep and resurrection?\n5. SANCTUARY - If mentioned, is the heavenly sanctuary doctrine clear?\n6. SECOND COMING - Is it presented with biblical urgency and hope?\n7. COVENANT - Is the relationship between old and new covenant clear?\n8. LAW AND GOSPEL - Is the proper relationship maintained?\n\nFor each relevant category:\n- isConsistent: true/false\n- concern: What's the issue (if any)\n- recommendation: How to fix it\n- severity: \"info\" / \"warning\" / \"critical\"\n\nReturn JSON:\n{\n  \"checks\": [\n    {\n      \"category\": \"grace\",\n      \"isConsistent\": true,\n      \"concern\": null,\n      \"recommendation\": null,\n      \"severity\": \"info\"\n    }\n  ],\n  \"overallConsistencyScore\": 90,\n  \"summary\": \"Brief assessment of doctrinal alignment\"\n}\n\nThis is not about being theologically correct in general - it's about consistency with SDA doctrinal system.");
    },
    historicalContextEnhancer: function (input) {
        return "You are a biblical historian writing pastor-ready historical context.\n\nPASSAGE: ".concat(input.mainPassage, "\nGENRE: ").concat(input.genre, "\nGENRE FOCUS: ").concat(input.genreFocus, "\n\nPASSAGE TEXT:\n").concat(input.passageText, "\n\nSURROUNDING CONTEXT:\n").concat(input.expandedPassageText, "\n\nBOOK METADATA JSON:\n").concat(input.bookMetadataJson || '{}', "\n\nHISTORICAL CONTEXT JSON:\n").concat(input.historicalContextJson || '{}', "\n\nCULTURAL CONTEXT JSON:\n").concat(input.culturalContextJson || '{}', "\n\nGEOGRAPHY CONTEXT JSON:\n").concat(input.geographyContextJson || '{}', "\n\nGEOGRAPHY NOTE:\n").concat(input.geographyNote, "\n\nLITERARY GUARDRAILS:\n").concat(input.literaryGuardrails.map(function (item) { return "- ".concat(item); }).join('\n'), "\n\nWRITE FOR THE PASTOR, NOT THE ENGINEER.\n\nRules:\n- Never use visible labels like fallback, template, custom, social, or placeholder.\n- Never say \"literary setting of Psalm\" or \"narrative or doctrinal flow\".\n- If the passage is a psalm, use poetic / wisdom / worship language.\n- If the passage is geography-light, say so naturally and lean on canonical and cultural context.\n- Keep the preacher inside the chapter and passage context; do not isolate the verse.\n- Explain how the context helps preaching.\n- If the passage is Psalm 37, note envy of the wicked, steps/path language, the reality of stumbling, and God's sustaining faithfulness.\n- If the passage is John 3:16, emphasize Nicodemus, new birth, belief, and eternal life.\n- If the passage is Luke 15:11-24, emphasize grumbling, honor-shame, inheritance, and homecoming.\n- If the passage is Revelation 14:6-12, keep it hopeful, worship-centered, and non-sensational.\n- If the passage is Exodus 20:8-11, emphasize covenant, liberation, creation, and Sabbath rest.\n\nReturn JSON:\n{\n  \"socialRealities\": [\n    {\n      \"aspect\": \"Specific community setting\",\n      \"description\": \"Concrete, passage-aware description\",\n      \"impact\": \"How this shapes preaching\"\n    }\n  ],\n  \"powerStructures\": [\n    {\n      \"structure\": \"Type of authority or influence\",\n      \"dynamics\": \"How it operates in the passage world\",\n      \"relevance\": \"Why it matters for the sermon\"\n    }\n  ],\n  \"economicContext\": [\n    {\n      \"factor\": \"Economic reality\",\n      \"description\": \"Concrete detail\"\n    }\n  ],\n  \"religiousClimate\": [\n    {\n      \"element\": \"Religious factor\",\n      \"description\": \"Concrete detail\",\n      \"tension\": \"The tension it creates\"\n    }\n  ],\n  \"audiencePressures\": [\n    {\n      \"pressure\": \"Specific pressure\",\n      \"source\": \"Where it comes from\",\n      \"pastoralResponse\": \"How the passage addresses it\"\n    }\n  ],\n  \"synthesisStatement\": \"2-3 sentence summary tying the context to preaching\"\n}\n\nReturn only JSON.");
    },
    sermonPatternGrowth: function (input) {
        return "You are analyzing a pastor's preaching patterns across ".concat(input.totalSermons, " sermons.\n\nSTYLE FREQUENCY: ").concat(input.styleFrequencyJson, "\nTHEME FREQUENCY: ").concat(input.themeFrequencyJson, "\nAPPLICATION BALANCE: ").concat(input.applicationBalanceJson, "\n\nRECENT PASSAGES: ").concat(input.recentPassages, "\nRECENT THEMES: ").concat(input.recentThemes, "\n\nTASK: Provide growth insights:\n\n1. STRENGTHS - What patterns show maturity?\n2. WEAKNESSES - What patterns reveal blind spots?\n   - Do they overemphasize application?\n   - Underemphasize Christ?\n   - Repeat same structure?\n   - Avoid prophetic tone?\n   - Avoid difficult texts?\n3. RECOMMENDATIONS - Specific growth areas\n\nReturn JSON:\n{\n  \"avgChristCentrality\": 75,\n  \"avgApplicationDepth\": 65,\n  \"avoidedTexts\": [\"Book or type of text avoided\"],\n  \"overusedIllustrations\": [\"Illustration type used too often\"],\n  \"growthInsights\": [\n    {\n      \"strength\": \"Specific strength\",\n      \"weakness\": \"Specific weakness\",\n      \"recommendation\": \"Actionable next step\"\n    }\n  ]\n}");
    },
    preachingStrategy: function (input) {
        return "You are a preaching strategist. Help select the optimal PREACHING GENRE and STRATEGY for this sermon.\n\nPASSAGE: ".concat(input.mainPassage, "\nTEXT: ").concat(input.passageText, "\n\nTHEME: ").concat(input.theme, "\nAUDIENCE: ").concat(input.audience, "\nGOALS: ").concat(input.goals, "\n\nTASK: Recommend the best preaching approach.\n\nGENRES (choose one):\n- expository: Verse-by-verse explanation\n- narrative: Story-driven, following biblical narrative\n- prophetic: Calling to repentance/action, urgent tone\n- apologetic: Defending faith, answering objections\n- revivalist: Stirring hearts, emotional appeal\n- teaching: Doctrinal instruction, concept-heavy\n- pastoral: Comforting, healing, shepherding\n- evangelistic: Gospel presentation, invitation-focused\n\nEMOTIONAL ARCS (choose one):\n- conviction_to_hope: Start with sin/need, end with grace\n- crisis_to_resolution: Present problem, offer solution\n- question_to_discovery: Raise questions, journey to answers\n- comfort_to_challenge: Start gentle, build to action\n- lament_to_praise: Acknowledge pain, move to worship\n\nAlso determine:\n- Tone (e.g., \"urgent\", \"contemplative\", \"celebratory\", \"pastoral\")\n- Target length in minutes\n- Tension level (0-100, how much discomfort to create)\n- Application density (0-100, how application-heavy)\n- Invitation driven (true/false)\n\nReturn JSON:\n{\n  \"recommendedGenre\": \"prophetic\",\n  \"genreRationale\": \"Why this genre fits the passage and goals\",\n  \"emotionalArc\": \"conviction_to_hope\",\n  \"tone\": \"urgent yet hopeful\",\n  \"targetLengthMinutes\": 35,\n  \"tensionLevel\": 75,\n  \"applicationDensity\": 60,\n  \"invitationDriven\": true,\n  \"structuralGuidance\": {\n    \"introduction\": \"How to open\",\n    \"bodyStructure\": \"How to organize the body\",\n    \"conclusion\": \"How to close\"\n  }\n}");
    },
    crossReferenceNarrative: function (input) {
        return "You are a biblical theologian creating NARRATIVE THREADS from cross-references.\n\nSOURCE VERSE: ".concat(input.sourceVerse, "\nTEXT: ").concat(input.sourceText, "\n\nCROSS-REFERENCES:\n").concat(input.crossReferencesText, "\n\nTASK: Instead of presenting cross-references as a list, create THEMATIC CHAINS that tell a story.\n\nExample:\n\"Grace transforms identity across covenant history\"\nChain: Ephesians 2:1-10 \u2192 Romans 5 \u2192 Titus 3 \u2192 Ezekiel 36 \u2192 Jeremiah 31\n\nFor each narrative thread:\n1. Create a compelling narrative title\n2. Describe the story arc\n3. Order the references chronologically or thematically\n4. Show each reference's contribution to the narrative\n5. Identify the redemptive movement\n\nReturn JSON array:\n[\n  {\n    \"narrativeTitle\": \"Title of the thematic chain\",\n    \"narrativeDescription\": \"The story this chain tells\",\n    \"chain\": [\n      {\n        \"reference\": \"Gen 3:15\",\n        \"era\": \"Creation/Fall\",\n        \"contribution\": \"What this reference adds to the narrative\",\n        \"order\": 1\n      }\n    ],\n    \"thematicThread\": \"One-sentence summary of the thread\",\n    \"redemptiveMovement\": \"How this moves redemptive history forward\"\n  }\n]\n\nCreate 2-3 narrative threads maximum. Make cross-references tell a story, not just be a database output.");
    },
    theologicalCenter: function (input) {
        return "You are a seasoned preaching mentor analyzing sermon alignment with the theological center of the passage.\n\nPASSAGE: ".concat(input.mainPassage, "\nTEXT: ").concat(input.passageText, "\n\nSERMON THEME: ").concat(input.theme, "\nOUTLINE POINTS: ").concat(input.outlinePoints, "\n\nTASK:\n1. Identify the DOMINANT THEOLOGICAL CENTER of this passage - the central claim, the main point God is making.\n2. Provide clear TEXTUAL WARRANT - which verses/phrases establish this center.\n3. Analyze if the sermon is ORBITING this center or deviating from it.\n4. Identify DEVIATIONS - points that drift from the center (rate severity: minor/moderate/major).\n5. Identify SECONDARY THEMES that should be suppressed or removed.\n6. Give an ALIGNMENT SCORE (0-100).\n\nReturn JSON:\n{\n  \"dominantCenter\": \"Clear statement of the passage's theological center\",\n  \"textualWarrant\": \"Specific verses and phrases that establish this\",\n  \"alignmentScore\": 85,\n  \"deviations\": [\n    {\n      \"point\": \"Outline point that deviates\",\n      \"severity\": \"moderate\",\n      \"explanation\": \"Why this deviates from the center\"\n    }\n  ],\n  \"secondaryThemes\": [\"Theme 1\", \"Theme 2\"],\n  \"suppressionSuggestions\": [\n    {\n      \"theme\": \"Secondary theme to remove\",\n      \"reason\": \"Why it weakens the sermon\",\n      \"impact\": \"What removing it accomplishes\"\n    }\n  ]\n}\n\nBe DECISIVE. Say \"This is weak\" or \"This is the strongest thread\" or \"This is distracting.\"");
    },
    blindSpotDetector: function (input) {
        return "You are a preaching mentor conducting a BLIND SPOT ANALYSIS. This adds intellectual honesty by revealing what the sermon is NOT saying.\n\nPASSAGE: ".concat(input.mainPassage, "\nTEXT: ").concat(input.passageText, "\n\nSERMON OUTLINE: ").concat(input.outlinePoints, "\nAPPLICATIONS: ").concat(input.applicationTexts, "\n\nTASK: Identify what this sermon is NOT addressing:\n\n1. THEMES NOT ADDRESSED - What themes are present in the passage but missing from the sermon?\n2. HARD VERSES AVOIDED - Which difficult/challenging verses in the passage are being skipped?\n3. DOCTRINAL TENSIONS MINIMIZED - What theological tensions are being smoothed over?\n4. APPLICATION IMBALANCE - Are applications skewed toward one category?\n   Categories: personal, communal, missional, doctrinal\n\nReturn JSON:\n{\n  \"themesNotAddressed\": [\"Theme 1\", \"Theme 2\"],\n  \"hardVersesAvoided\": [\"Verse ref 1\", \"Verse ref 2\"],\n  \"doctrinalTensionsMinimized\": [\n    {\n      \"tension\": \"Description of tension\",\n      \"howMinimized\": \"How the sermon avoids it\"\n    }\n  ],\n  \"applicationImbalance\": [\n    {\n      \"category\": \"personal\",\n      \"count\": 5,\n      \"recommendation\": \"Too heavy on personal, add communal applications\"\n    }\n  ],\n  \"overallAssessment\": \"Summary of blind spots and their impact\"\n}\n\nBe honest. This section exists to expose weaknesses, not validate the sermon.");
    },
};
