"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScripturePrompts = void 0;
exports.ScripturePrompts = {
    interpretiveHighlights: function (input) {
        return "Analyze this Bible verse for interpretive challenges. Return JSON only.\n\nReference: ".concat(input.reference, "\nText: ").concat(input.verseText, "\n\nIdentify phrases with:\n1. Grammatical ambiguity (unclear syntax or word meaning)\n2. Theological debate (different doctrinal interpretations)\n3. Textual variants (manuscript differences)\n4. Contextual tension (apparent contradictions or difficult passages)\n\nReturn JSON array:\n[\n  {\n    \"phrase\": \"exact phrase from text\",\n    \"type\": \"grammatical_ambiguity|theological_debate|textual_variant|contextual_tension\",\n    \"options\": [\n      {\n        \"view\": \"interpretation name\",\n        \"explanation\": \"brief explanation\",\n        \"proponents\": [\"tradition or scholar\"]\n      }\n    ],\n    \"significance\": \"why this matters\"\n  }\n]\n\nRules:\n- Only include genuine scholarly debates\n- Be honest about uncertainty\n- Cite specific traditions when possible\n- No markdown, just JSON");
    },
    crossReferenceRefine: function (input) {
        return "Refine these ranked biblical cross references for preaching use.\n\nSource Verse: ".concat(input.sourceVerse, "\nSource Text: ").concat(input.sourceText, "\n\nCandidates JSON:\n").concat(input.candidatesJson, "\n\nReturn JSON array of same length and order with fields:\n[\n  {\n    \"reference\": \"string\",\n    \"category\": \"thematic|quotation|typology|prophetic_fulfillment|narrative_continuation|interpretive_tension|lexical\",\n    \"tier\": \"primary|secondary|illustrative\",\n    \"relevanceScore\": 0-100,\n    \"connectionExplanation\": \"short explanation\",\n    \"themes\": [\"theme1\",\"theme2\"]\n  }\n]\n\nRules:\n- Keep references unchanged.\n- Improve explanation clarity for sermon use.\n- Keep categories/tier conservative.\n- Return JSON only.");
    },
    perVerseContext: function (input) {
        return "".concat(input.languageInstruction, " Return valid JSON only. You are generating pastor-facing historical, cultural, and geographical context.\n\nReference: ").concat(input.reference, "\nRequested language: ").concat(input.targetLanguage, "\nGenre hint: ").concat(input.genreHint, "\nTheme hint: ").concat(input.themeHint, "\nContext hint: ").concat(input.contextHint, "\nMotif hint: ").concat(input.motifHint, "\n\nPassage Text:\n").concat(input.passageText, "\n\nReturn this exact JSON shape:\n{\n  \"status\": \"ready\",\n  \"reference\": \"").concat(input.reference, "\",\n  \"language\": \"").concat(input.targetLanguage, "\",\n  \"genre\": \"Genre label for pastors\",\n  \"sections\": [\n    {\n      \"title\": \"Historical Context\",\n      \"content\": \"...\"\n    },\n    {\n      \"title\": \"Cultural Context\",\n      \"content\": \"...\"\n    },\n    {\n      \"title\": \"Geographical / Literary Setting\",\n      \"content\": \"...\"\n    },\n    {\n      \"title\": \"Significance for Preaching\",\n      \"content\": \"...\"\n    },\n    {\n      \"title\": \"Pastoral Application\",\n      \"content\": \"...\"\n    }\n  ],\n  \"warnings\": [],\n  \"source\": \"llm-generated\"\n}\n\nRules:\n- Do not include fallback, social, custom, template, placeholder, debug, TODO, undefined, or null language.\n- Do not use generic filler.\n- Do not say \"The passage belongs to the literary setting of...\"\n- Do not say \"immediate narrative or doctrinal flow\".\n- Do not say \"Exact geography is unavailable\".\n- Do not say \"Helps move from background to sermon\".\n- Do not invent specific historical facts.\n- Identify genre before writing.\n- For Psalms, use poetic, wisdom, and worship framing, not narrative framing.\n- If geography is not central, explain literary and canonical setting naturally.\n- Do not quote partial verses.\n- Keep the verse tied to its chapter and book context.\n- Write for preaching use, not academic display.\n- Return JSON only.");
    },
    perVerseContextRepair: function (input) {
        return "".concat(input.languageInstruction, " Return valid JSON only. You are correcting a pastor-facing historical-context response.\n\nReference: ").concat(input.reference, "\nRequested language: ").concat(input.targetLanguage, "\nGenre hint: ").concat(input.genreHint, "\nTheme hint: ").concat(input.themeHint, "\nContext hint: ").concat(input.contextHint, "\nMotif hint: ").concat(input.motifHint, "\n\nPassage Text:\n").concat(input.passageText, "\n\nPrevious Response:\n").concat(input.previousResponse, "\n\nValidation Errors:\n").concat(input.validationErrors.map(function (error) { return "- ".concat(error); }).join('\n'), "\n\nReturn the corrected JSON in this exact shape:\n{\n  \"status\": \"ready\",\n  \"reference\": \"").concat(input.reference, "\",\n  \"language\": \"").concat(input.targetLanguage, "\",\n  \"genre\": \"Genre label for pastors\",\n  \"sections\": [\n    {\n      \"title\": \"Historical Context\",\n      \"content\": \"...\"\n    },\n    {\n      \"title\": \"Cultural Context\",\n      \"content\": \"...\"\n    },\n    {\n      \"title\": \"Geographical / Literary Setting\",\n      \"content\": \"...\"\n    },\n    {\n      \"title\": \"Significance for Preaching\",\n      \"content\": \"...\"\n    },\n    {\n      \"title\": \"Pastoral Application\",\n      \"content\": \"...\"\n    }\n  ],\n  \"warnings\": [],\n  \"source\": \"llm-generated\"\n}\n\nRules:\n- Do not use fallback, social, custom, template, placeholder, debug, TODO, undefined, or null language.\n- Do not include generic filler lines.\n- Do not repeat the validation errors.\n- Do not quote partial verses.\n- Keep it passage-aware and pastor-focused.\n- Return JSON only.");
    },
    interpretiveChallengesData: function (input) {
        return "".concat(input.languageInstruction, " Devuelve solo JSON v\u00E1lido. Eres un erudito b\u00EDblico que identifica tensiones interpretativas y perspectivas teol\u00F3gicas.\n\nPassage Reference: ").concat(input.passage, "\n\nPassage Text:\n").concat(input.passageText, "\n\nFormato JSON:\n{\n  \"challenge\": \"Main interpretive question or difficulty\",\n  \"views\": [\n    {\n      \"viewName\": \"Name of interpretive view\",\n      \"summary\": \"Brief summary of this view\",\n      \"proponents\": \"Optional: who holds this view\",\n      \"keyArguments\": [\"Argument 1\", \"Argument 2\", \"Argument 3\"]\n    }\n  ],\n  \"sdaPerspective\": {\n    \"position\": \"SDA theological position\",\n    \"reasoning\": \"Why SDA theology holds this position\",\n    \"supportingTexts\": [\"Reference 1\", \"Reference 2\"]\n  }\n}\n\nReglas:\n- Devuelve 2-4 perspectivas reales.\n- Cada perspectiva debe tener 2-3 argumentos breves.\n- Si no hay desaf\u00EDo importante, usa null en challenge.\n- No uses markdown ni texto fuera del JSON.");
    },
    structuralAnalysis: function (input) {
        return "".concat(input.languageInstruction, "\n\nYou are a biblical scholar analyzing the literary structure of scripture passages.\n\nPassage Reference: ").concat(input.passage, "\n\nPassage Text:\n").concat(input.passageText, "\n\nProvide a detailed structural analysis in the following JSON format:\n{\n  \"literaryGenre\": \"Genre (e.g., Narrative, Poetry, Apocalyptic, Legal, Wisdom, Gospel, Epistle)\",\n  \"structure\": [\n    {\n      \"verses\": \"verse range\",\n      \"type\": \"introduction|body|conclusion|transition|climax|inclusio\",\n      \"description\": \"Description of this structural element\"\n    }\n  ],\n  \"chiasm\": {\n    \"pattern\": \"Pattern notation (e.g., A-B-C-B'-A')\",\n    \"elements\": [\n      {\n        \"label\": \"A\",\n        \"verses\": \"verse range\",\n        \"content\": \"Brief description\"\n      }\n    ]\n  },\n  \"parallelism\": [\n    {\n      \"type\": \"synonymous|antithetic|synthetic|emblematic\",\n      \"verses\": \"verse range\",\n      \"lineA\": \"First line\",\n      \"lineB\": \"Second line\"\n    }\n  ]\n}\n\nGuidelines:\n- Identify the literary genre accurately\n- Break down the passage into 3-6 structural elements\n- Note transitions, climaxes, and literary devices\n- ALWAYS create a chiastic structure with at least 3 elements (A-B-A' minimum), even if the passage doesn't have an obvious chiasm - identify thematic or conceptual parallels\n- For poetry, identify parallelism patterns when present\n- Parallelism is optional - only include if clearly present\n- Return ONLY valid JSON, no markdown or extra text");
    },
    verseContextualCommentary: function (input) {
        return "".concat(input.languageInstruction, " Provide a brief 2-3 sentence contextual overview of ").concat(input.reference, ". Include:\n- What is happening in this passage\n- Where it fits in the book/narrative\n- Key theological significance\n\nBe concise and pastor-focused. Language: ").concat(input.languageLabel);
    },
    verseLlmCommentary: function (input) {
        return "".concat(input.languageInstruction, " You are a biblical scholar providing verse commentary for pastors.\n\nAnalyze ").concat(input.reference, " and provide 3-4 concise commentary notes covering:\n\n1. **Context**: What's happening in this passage? Where does it fit in the book?\n2. **Key Words**: Any significant Greek/Hebrew words or phrases worth noting?\n3. **Historical/Cultural**: Relevant historical or cultural background\n4. **Theological**: Main theological significance or application\n\nFormat as JSON:\n{\n  \"notes\": [\n    {\n      \"type\": \"context\" | \"word\" | \"historical\" | \"theological\",\n      \"content\": \"...\",\n      \"source\": \"...\"\n    }\n  ]\n}\n\nKeep each note to 2-3 sentences. Be practical and pastor-focused. Language: ").concat(input.languageLabel);
    },
    basicStructuralAnalysis: function (input) {
        return "Analyze the passage structure and return JSON only.\n\nPassage: ".concat(input.reference, "\n\nText:\n").concat(input.passageText, "\n\nReturn JSON with keys:\n{\n  \"repeatedPhrases\": [\"...\"],\n  \"imperatives\": [\"...\"],\n  \"promises\": [\"...\"],\n  \"conditions\": [\"...\"],\n  \"narrativeShifts\": [\"...\"],\n  \"literaryMarkers\": [\"...\"],\n  \"chiasticStructure\": \"...\",\n  \"outline\": [\"Verse: Summary\"]\n}\n\nRules:\n- Ground all points in verses.\n- If unsure, say so in the relevant field.\n- No markdown.");
    },
    basicInterpretiveChallenges: function (input) {
        return "Identify interpretive challenges or debated phrases in this passage.\n\nPassage: ".concat(input.reference, "\nText:\n").concat(input.passageText, "\n\nReturn ONLY JSON:\n{\n  \"challenges\": [\n    {\n      \"phrase\": \"...\",\n      \"issue\": \"...\",\n      \"views\": [\"...\", \"...\"],\n      \"verses\": [\"Book 1:1\"]\n    }\n  ]\n}\n\nRules:\n- Include verses for each challenge.\n- If none, return an empty array.\n- No markdown.");
    },
    wordStudyInsights: function (input) {
        return "Provide advanced word study insights as JSON only.\n\nWord: ".concat(input.word, "\nLanguage: ").concat(input.language, "\nContext: ").concat(input.context, "\nOutput Language: ").concat(input.outputLanguageLabel, "\n\nReturn JSON:\n{\n  \"rootWord\": \"...\",\n  \"semanticRange\": [\"...\"],\n  \"grammarInsights\": {\n    \"tense\": \"...\",\n    \"voice\": \"...\",\n    \"mood\": \"...\",\n    \"case\": \"...\",\n    \"number\": \"...\",\n    \"gender\": \"...\",\n    \"notes\": \"...\"\n  },\n  \"nuanceNotes\": [\"...\"],\n  \"commonTranslations\": [\"...\"],\n  \"exampleReferences\": [\"Book 1:1\"]\n}\n\nRules:\n- If unsure, say so in the relevant field.\n- All human-readable values must be written in ").concat(input.outputLanguageLabel, ".\n- No markdown, no extra commentary.");
    },
    wordStudySuggestions: function (input) {
        return "Extract the most important ".concat(input.sourceLanguageLabel, " study words for this Bible passage.\n\nReference: ").concat(input.reference, "\nPassage Text:\n").concat(input.passageText, "\nOutput language for gloss/reason: ").concat(input.outputLanguageLabel, "\n\nReturn JSON only:\n[\n  {\n    \"term\": \"string\",\n    \"transliteration\": \"string\",\n    \"gloss\": \"string\",\n    \"reason\": \"short reason this term matters for interpreting the passage\",\n    \"language\": \"").concat(input.sourceLanguage, "\"\n  }\n]\n\nRules:\n- Return 5-8 terms max.\n- Prioritize doctrinally central and structurally central terms.\n- Do not return duplicates.\n- No markdown, no commentary.");
    },
    translateTextToSpanish: function (input) {
        return "Translate to Spanish.\n\nRules:\n- Keep Greek/Hebrew words, Strong's identifiers, and Bible references unchanged.\n- Return only the translated text, no quotes, no markdown.\n\nText:\n".concat(input);
    },
    translationComparisonRepair: function (input) {
        if (input.isSpanish) {
            return "Convierte la siguiente respuesta en JSON V\u00C1LIDO con esta forma exacta.\nNo inventes contenido. Si falta algo, usa arreglos vac\u00EDos y una oraci\u00F3n breve en overallAssessment.\nDevuelve SOLO JSON.\n\n{\n  \"keyDifferences\": [\n    {\n      \"category\": \"theological_term\",\n      \"translations\": [],\n      \"difference\": \"\",\n      \"explanation\": \"\",\n      \"significance\": \"medium\"\n    }\n  ],\n  \"analysis\": {\n    \"verbDifferences\": [],\n    \"theologicalTermDifferences\": [],\n    \"literalVsDynamic\": [],\n    \"overallAssessment\": \"\"\n  }\n}\n\nRESPUESTA ORIGINAL:\n".concat(input.rawResponse);
        }
        return "Convert the following response into VALID JSON with this exact shape.\nDo not invent content. If data is missing, use empty arrays and a short overallAssessment sentence.\nReturn ONLY JSON.\n\n{\n  \"keyDifferences\": [\n    {\n      \"category\": \"theological_term\",\n      \"translations\": [],\n      \"difference\": \"\",\n      \"explanation\": \"\",\n      \"significance\": \"medium\"\n    }\n  ],\n  \"analysis\": {\n    \"verbDifferences\": [],\n    \"theologicalTermDifferences\": [],\n    \"literalVsDynamic\": [],\n    \"overallAssessment\": \"\"\n  }\n}\n\nORIGINAL RESPONSE:\n".concat(input.rawResponse);
    },
    translationComparisonAnalyze: function (input) {
        if (input.isSpanish) {
            return "Responde \u00DANICAMENTE en espa\u00F1ol. No uses ingl\u00E9s en ning\u00FAn campo de texto (difference, explanation, analysis, overallAssessment, etc.).\nEres un erudito b\u00EDblico que analiza diferencias de traducci\u00F3n para pastores.\n\n**Pasaje**: ".concat(input.reference, "\n\n**Traducciones**:\n").concat(input.translationTexts, "\n\nAnaliza las diferencias clave entre estas traducciones y entrega:\n\n1. **Diferencias clave**: 3-5 diferencias significativas (t\u00E9rminos teol\u00F3gicos, verbos, adiciones/omisiones, literal vs din\u00E1mico)\n2. **An\u00E1lisis**:\n   - Diferencias verbales\n   - Diferencias de t\u00E9rminos teol\u00F3gicos\n   - Enfoque literal vs din\u00E1mico\n   - Evaluaci\u00F3n general\n\nFormato JSON:\n{\n  \"keyDifferences\": [\n    {\n      \"category\": \"theological_term\" | \"verb_difference\" | \"literal_vs_dynamic\" | \"addition_omission\",\n      \"translations\": [\"RVR1960: texto\", \"NBLA: texto\"],\n      \"difference\": \"Descripci\u00F3n breve en espa\u00F1ol\",\n      \"explanation\": \"Explicaci\u00F3n detallada en espa\u00F1ol\",\n      \"significance\": \"high\" | \"medium\" | \"low\"\n    }\n  ],\n  \"analysis\": {\n    \"verbDifferences\": [\"diferencia 1\"],\n    \"theologicalTermDifferences\": [\"diferencia 1\"],\n    \"literalVsDynamic\": [\"observaci\u00F3n 1\"],\n    \"overallAssessment\": \"Resumen general en espa\u00F1ol\"\n  }\n}\n\nS\u00E9 conciso, pr\u00E1ctico y pastoral. Devuelve SOLO JSON v\u00E1lido.");
        }
        return "Respond in English. You are a biblical scholar analyzing translation differences for pastors.\n\n**Passage**: ".concat(input.reference, "\n\n**Translations**:\n").concat(input.translationTexts, "\n\nAnalyze the key differences between these translations and provide:\n\n1. **Key Differences**: 3-5 significant differences (theological terms, verb choices, additions/omissions, literal vs dynamic)\n2. **Analysis**:\n   - Verb differences\n   - Theological term differences\n   - Literal vs dynamic translation approaches\n   - Overall assessment\n\nFormat as JSON:\n{\n  \"keyDifferences\": [\n    {\n      \"category\": \"theological_term\" | \"verb_difference\" | \"literal_vs_dynamic\" | \"addition_omission\",\n      \"translations\": [\"KJV: text\", \"NIV: text\"],\n      \"difference\": \"Brief description\",\n      \"explanation\": \"Detailed explanation\",\n      \"significance\": \"high\" | \"medium\" | \"low\"\n    }\n  ],\n  \"analysis\": {\n    \"verbDifferences\": [\"difference 1\", \"difference 2\"],\n    \"theologicalTermDifferences\": [\"difference 1\"],\n    \"literalVsDynamic\": [\"observation 1\"],\n    \"overallAssessment\": \"Summary of main differences and their significance\"\n  }\n}\n\nBe concise, practical, and pastor-focused. Highlight differences that affect interpretation or application.");
    },
    translationComparisonSpanishEnforcer: function (resultJson) {
        return "Traduce al espa\u00F1ol TODOS los valores de texto del siguiente JSON.\nNo cambies claves, estructura, categor\u00EDas ni niveles de significancia.\nDevuelve SOLO JSON v\u00E1lido.\n\nJSON:\n".concat(resultJson);
    },
    canonicalThemes: function (input) {
        return "".concat(input.languageInstruction, "You are a biblical scholar identifying canonical themes that trace through Scripture.\n\nPassage Reference: ").concat(input.reference, "\n\nPassage Text:\n").concat(input.passageText, "\n\nIdentify 3-4 major theological themes in this passage and trace them across Scripture.\n\nJSON format:\n{\n  \"themes\": [\n    {\n      \"theme\": \"...\",\n      \"description\": \"...\",\n      \"explanation\": \"...\",\n      \"canonicalMovement\": \"...\",\n      \"category\": \"...\",\n      \"verses\": [\n        {\n          \"reference\": \"...\",\n          \"snippet\": \"...\",\n          \"explanation\": \"...\",\n          \"stage\": \"...\",\n          \"testament\": \"...\",\n          \"era\": \"...\"\n        }\n      ]\n    }\n  ]\n}\n\nRules:\n- Use 4-6 verses per theme.\n- Include the current passage in one verse list entry with \"YOU ARE HERE\".\n- Keep themes theologically meaningful and canonically progressive.\n- No markdown or extra text.");
    },
    passageSummary: function (input) {
        return "".concat(input.languageInstruction, " You are a biblical scholar providing interpretive guidance for pastors studying Scripture.\n\nPassage Reference: ").concat(input.reference, "\n\nPassage Text:\n").concat(input.passageText, "\n\nAnalyze this passage and provide:\n\n1. **Summary** (2-3 sentences): What happens in this passage? What is the basic content?\n\n2. **Passage Movement** (if narrative, 3-5 steps): Break down the flow of the passage step by step. If it's not narrative (e.g., poetry, epistle), skip this section.\n\n3. **Interpretive Center** (1-2 sentences): What is the theological heart of this passage? What is the main claim or truth being communicated?\n\n4. **Main Tension** (1-2 sentences): What is the primary theological or interpretive tension in this passage? What question or difficulty does it raise?\n\nFormat your response as JSON:\n{\n  \"summary\": \"...\",\n  \"movement\": [\"step 1\", \"step 2\", \"step 3\"] or [],\n  \"interpretiveCenter\": \"...\",\n  \"mainTension\": \"...\"\n}\n\nBe concise, theologically precise, and pastor-focused.");
    },
    studySynthesis: function (input) {
        return "".concat(input.languageInstruction, " You are a biblical theologian synthesizing study insights for pastors preparing sermons.\n\nPassage Reference: ").concat(input.reference, "\n\nPassage Text:\n").concat(input.passageText, "\n\nAfter analyzing this passage through multiple interpretive lenses (structure, context, themes, challenges), provide a unified theological synthesis:\n\n1. **Central Claim** (1-2 sentences): What is the core theological truth this passage communicates? State it as a clear, declarative claim.\n\n2. **Canonical Significance** (2-3 sentences): How does this passage fit into the larger biblical storyline? What role does it play in God's unfolding revelation?\n\n3. **Pastoral Takeaway** (2-3 sentences): What does this passage mean for God's people today? How should it shape faith and practice?\n\n4. **Preaching Focus** (1-2 sentences): What is the sermon-ready angle? What should a pastor emphasize when preaching this text?\n\nFormat your response as JSON:\n{\n  \"centralClaim\": \"...\",\n  \"canonicalSignificance\": \"...\",\n  \"pastoralTakeaway\": \"...\",\n  \"preachingFocus\": \"...\"\n}\n\nBe theologically precise, pastorally practical, and sermon-focused.");
    },
    sanctuaryOrProphecyConnections: function (input) {
        if (input.mode === 'sanctuary') {
            return "".concat(input.languageInstruction, "\n\nYou are a Seventh-day Adventist biblical theologian.\nTask: Generate sanctuary connections for the passage below, following Adventist doctrine only.\nDo not use non-Adventist interpretive frameworks.\nGround every connection in explicit Scripture references.\n\nPassage: ").concat(input.passage, "\nPassage Text:\n").concat(input.passageText, "\n\nReturn JSON exactly in this shape:\n{\n  \"connections\": [\n    {\n      \"sourcePassage\": \"Book X:Y-Z\",\n      \"targetPassages\": [\"Book A:B-C\", \"Book D:E-F\"],\n      \"connectionType\": \"type_antitype|parallel|fulfillment|thematic\",\n      \"description\": \"1-2 sentences, Adventist framing only\"\n    }\n  ]\n}\n\nRules:\n- Return 1 to 5 connections.\n- Keep description concise and specific.\n- Use only canonical Bible references.\n- connectionType must be one of: type_antitype, parallel, fulfillment, thematic.\n- No extra fields.");
        }
        return "".concat(input.languageInstruction, "\n\nYou are a Seventh-day Adventist biblical theologian.\nTask: Generate prophecy connections for the passage below, following Adventist doctrine only.\nDo not use non-Adventist interpretive frameworks.\nGround every connection in explicit Scripture references.\n\nPassage: ").concat(input.passage, "\nPassage Text:\n").concat(input.passageText, "\n\nReturn JSON exactly in this shape:\n{\n  \"connections\": [\n    {\n      \"passage\": \"Book X:Y-Z\",\n      \"connectedPassages\": [\"Book A:B-C\", \"Book D:E-F\"],\n      \"theme\": \"short Adventist prophetic theme\",\n      \"description\": \"1-2 sentences, Adventist framing only\"\n    }\n  ]\n}\n\nRules:\n- Return 1 to 5 connections.\n- Keep theme and description concise and specific.\n- Use only canonical Bible references.\n- No extra fields.");
    },
};
